[2025-07-28 01:02:52] laravel.EMERGENCY: Unable to create configured logger. Using emergency logger. {"exception":"[object] (InvalidArgumentException(code: 0): Log [] is not defined. at C:\\laragon\\www\\feelback-docker\\vendor\\laravel\\framework\\src\\Illuminate\\Log\\LogManager.php:224)
[stacktrace]
#0 C:\\laragon\\www\\feelback-docker\\vendor\\laravel\\framework\\src\\Illuminate\\Log\\LogManager.php(138): Illuminate\\Log\\LogManager->resolve(NULL, NULL)
#1 C:\\laragon\\www\\feelback-docker\\vendor\\laravel\\framework\\src\\Illuminate\\Log\\LogManager.php(125): Illuminate\\Log\\LogManager->get(NULL)
#2 C:\\laragon\\www\\feelback-docker\\vendor\\laravel\\framework\\src\\Illuminate\\Log\\LogManager.php(693): Illuminate\\Log\\LogManager->driver()
#3 C:\\laragon\\www\\feelback-docker\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Exceptions\\Handler.php(375): Illuminate\\Log\\LogManager->error('Class \"Tymon\\\\JW...', Array)
#4 C:\\laragon\\www\\feelback-docker\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Exceptions\\Handler.php(336): Illuminate\\Foundation\\Exceptions\\Handler->reportThrowable(Object(Error))
#5 C:\\laragon\\www\\feelback-docker\\app\\Exceptions\\Handler.php(37): Illuminate\\Foundation\\Exceptions\\Handler->report(Object(Error))
#6 C:\\laragon\\www\\feelback-docker\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Console\\Kernel.php(617): App\\Exceptions\\Handler->report(Object(Error))
#7 C:\\laragon\\www\\feelback-docker\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Console\\Kernel.php(198): Illuminate\\Foundation\\Console\\Kernel->reportException(Object(Error))
#8 Command line code(1): Illuminate\\Foundation\\Console\\Kernel->handle(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#9 {main}
"} 
[2025-07-28 01:02:52] laravel.ERROR: Class "Tymon\JWTAuth\Providers\JWT\Provider" not found {"exception":"[object] (Error(code: 0): Class \"Tymon\\JWTAuth\\Providers\\JWT\\Provider\" not found at C:\\laragon\\www\\feelback-docker\\config\\jwt.php:134)
[stacktrace]
#0 C:\\laragon\\www\\feelback-docker\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Bootstrap\\LoadConfiguration.php(91): require()
#1 C:\\laragon\\www\\feelback-docker\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Bootstrap\\LoadConfiguration.php(72): Illuminate\\Foundation\\Bootstrap\\LoadConfiguration->loadConfigurationFile(Object(Illuminate\\Config\\Repository), 'jwt', 'C:\\\\laragon\\\\www\\\\...', Array)
#2 C:\\laragon\\www\\feelback-docker\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Bootstrap\\LoadConfiguration.php(39): Illuminate\\Foundation\\Bootstrap\\LoadConfiguration->loadConfigurationFiles(Object(Illuminate\\Foundation\\Application), Object(Illuminate\\Config\\Repository))
#3 C:\\laragon\\www\\feelback-docker\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Application.php(309): Illuminate\\Foundation\\Bootstrap\\LoadConfiguration->bootstrap(Object(Illuminate\\Foundation\\Application))
#4 C:\\laragon\\www\\feelback-docker\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Console\\Kernel.php(470): Illuminate\\Foundation\\Application->bootstrapWith(Array)
#5 C:\\laragon\\www\\feelback-docker\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Console\\Kernel.php(194): Illuminate\\Foundation\\Console\\Kernel->bootstrap()
#6 Command line code(1): Illuminate\\Foundation\\Console\\Kernel->handle(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#7 {main}
"} 
[2025-07-28 01:02:52] laravel.EMERGENCY: Unable to create configured logger. Using emergency logger. {"exception":"[object] (InvalidArgumentException(code: 0): Log [] is not defined. at C:\\laragon\\www\\feelback-docker\\vendor\\laravel\\framework\\src\\Illuminate\\Log\\LogManager.php:224)
[stacktrace]
#0 C:\\laragon\\www\\feelback-docker\\vendor\\laravel\\framework\\src\\Illuminate\\Log\\LogManager.php(138): Illuminate\\Log\\LogManager->resolve(NULL, NULL)
#1 C:\\laragon\\www\\feelback-docker\\vendor\\laravel\\framework\\src\\Illuminate\\Log\\LogManager.php(125): Illuminate\\Log\\LogManager->get(NULL)
#2 C:\\laragon\\www\\feelback-docker\\vendor\\laravel\\framework\\src\\Illuminate\\Log\\LogManager.php(693): Illuminate\\Log\\LogManager->driver()
#3 C:\\laragon\\www\\feelback-docker\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Exceptions\\Handler.php(375): Illuminate\\Log\\LogManager->error('Class \"Tymon\\\\JW...', Array)
#4 C:\\laragon\\www\\feelback-docker\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Exceptions\\Handler.php(336): Illuminate\\Foundation\\Exceptions\\Handler->reportThrowable(Object(Error))
#5 C:\\laragon\\www\\feelback-docker\\app\\Exceptions\\Handler.php(37): Illuminate\\Foundation\\Exceptions\\Handler->report(Object(Error))
#6 C:\\laragon\\www\\feelback-docker\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Console\\Kernel.php(617): App\\Exceptions\\Handler->report(Object(Error))
#7 C:\\laragon\\www\\feelback-docker\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Console\\Kernel.php(198): Illuminate\\Foundation\\Console\\Kernel->reportException(Object(Error))
#8 Command line code(1): Illuminate\\Foundation\\Console\\Kernel->handle(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#9 {main}
"} 
[2025-07-28 01:02:52] laravel.ERROR: Class "Tymon\JWTAuth\Providers\JWT\Provider" not found {"exception":"[object] (Error(code: 0): Class \"Tymon\\JWTAuth\\Providers\\JWT\\Provider\" not found at C:\\laragon\\www\\feelback-docker\\config\\jwt.php:134)
[stacktrace]
#0 C:\\laragon\\www\\feelback-docker\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Bootstrap\\LoadConfiguration.php(91): require()
#1 C:\\laragon\\www\\feelback-docker\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Bootstrap\\LoadConfiguration.php(72): Illuminate\\Foundation\\Bootstrap\\LoadConfiguration->loadConfigurationFile(Object(Illuminate\\Config\\Repository), 'jwt', 'C:\\\\laragon\\\\www\\\\...', Array)
#2 C:\\laragon\\www\\feelback-docker\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Bootstrap\\LoadConfiguration.php(39): Illuminate\\Foundation\\Bootstrap\\LoadConfiguration->loadConfigurationFiles(Object(Illuminate\\Foundation\\Application), Object(Illuminate\\Config\\Repository))
#3 C:\\laragon\\www\\feelback-docker\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Application.php(309): Illuminate\\Foundation\\Bootstrap\\LoadConfiguration->bootstrap(Object(Illuminate\\Foundation\\Application))
#4 C:\\laragon\\www\\feelback-docker\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Console\\Kernel.php(470): Illuminate\\Foundation\\Application->bootstrapWith(Array)
#5 C:\\laragon\\www\\feelback-docker\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Console\\Kernel.php(194): Illuminate\\Foundation\\Console\\Kernel->bootstrap()
#6 Command line code(1): Illuminate\\Foundation\\Console\\Kernel->handle(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#7 {main}
"} 
[2025-07-28 01:02:56] laravel.EMERGENCY: Unable to create configured logger. Using emergency logger. {"exception":"[object] (InvalidArgumentException(code: 0): Log [] is not defined. at C:\\laragon\\www\\feelback-docker\\vendor\\laravel\\framework\\src\\Illuminate\\Log\\LogManager.php:224)
[stacktrace]
#0 C:\\laragon\\www\\feelback-docker\\vendor\\laravel\\framework\\src\\Illuminate\\Log\\LogManager.php(138): Illuminate\\Log\\LogManager->resolve(NULL, NULL)
#1 C:\\laragon\\www\\feelback-docker\\vendor\\laravel\\framework\\src\\Illuminate\\Log\\LogManager.php(125): Illuminate\\Log\\LogManager->get(NULL)
#2 C:\\laragon\\www\\feelback-docker\\vendor\\laravel\\framework\\src\\Illuminate\\Log\\LogManager.php(693): Illuminate\\Log\\LogManager->driver()
#3 C:\\laragon\\www\\feelback-docker\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Exceptions\\Handler.php(375): Illuminate\\Log\\LogManager->error('Class \"Tymon\\\\JW...', Array)
#4 C:\\laragon\\www\\feelback-docker\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Exceptions\\Handler.php(336): Illuminate\\Foundation\\Exceptions\\Handler->reportThrowable(Object(Error))
#5 C:\\laragon\\www\\feelback-docker\\app\\Exceptions\\Handler.php(37): Illuminate\\Foundation\\Exceptions\\Handler->report(Object(Error))
#6 C:\\laragon\\www\\feelback-docker\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Console\\Kernel.php(617): App\\Exceptions\\Handler->report(Object(Error))
#7 C:\\laragon\\www\\feelback-docker\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Console\\Kernel.php(198): Illuminate\\Foundation\\Console\\Kernel->reportException(Object(Error))
#8 Command line code(1): Illuminate\\Foundation\\Console\\Kernel->handle(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#9 {main}
"} 
[2025-07-28 01:02:56] laravel.ERROR: Class "Tymon\JWTAuth\Providers\JWT\Provider" not found {"exception":"[object] (Error(code: 0): Class \"Tymon\\JWTAuth\\Providers\\JWT\\Provider\" not found at C:\\laragon\\www\\feelback-docker\\config\\jwt.php:134)
[stacktrace]
#0 C:\\laragon\\www\\feelback-docker\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Bootstrap\\LoadConfiguration.php(91): require()
#1 C:\\laragon\\www\\feelback-docker\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Bootstrap\\LoadConfiguration.php(72): Illuminate\\Foundation\\Bootstrap\\LoadConfiguration->loadConfigurationFile(Object(Illuminate\\Config\\Repository), 'jwt', 'C:\\\\laragon\\\\www\\\\...', Array)
#2 C:\\laragon\\www\\feelback-docker\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Bootstrap\\LoadConfiguration.php(39): Illuminate\\Foundation\\Bootstrap\\LoadConfiguration->loadConfigurationFiles(Object(Illuminate\\Foundation\\Application), Object(Illuminate\\Config\\Repository))
#3 C:\\laragon\\www\\feelback-docker\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Application.php(309): Illuminate\\Foundation\\Bootstrap\\LoadConfiguration->bootstrap(Object(Illuminate\\Foundation\\Application))
#4 C:\\laragon\\www\\feelback-docker\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Console\\Kernel.php(470): Illuminate\\Foundation\\Application->bootstrapWith(Array)
#5 C:\\laragon\\www\\feelback-docker\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Console\\Kernel.php(194): Illuminate\\Foundation\\Console\\Kernel->bootstrap()
#6 Command line code(1): Illuminate\\Foundation\\Console\\Kernel->handle(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#7 {main}
"} 
[2025-07-28 01:02:58] laravel.EMERGENCY: Unable to create configured logger. Using emergency logger. {"exception":"[object] (InvalidArgumentException(code: 0): Log [] is not defined. at C:\\laragon\\www\\feelback-docker\\vendor\\laravel\\framework\\src\\Illuminate\\Log\\LogManager.php:224)
[stacktrace]
#0 C:\\laragon\\www\\feelback-docker\\vendor\\laravel\\framework\\src\\Illuminate\\Log\\LogManager.php(138): Illuminate\\Log\\LogManager->resolve(NULL, NULL)
#1 C:\\laragon\\www\\feelback-docker\\vendor\\laravel\\framework\\src\\Illuminate\\Log\\LogManager.php(125): Illuminate\\Log\\LogManager->get(NULL)
#2 C:\\laragon\\www\\feelback-docker\\vendor\\laravel\\framework\\src\\Illuminate\\Log\\LogManager.php(693): Illuminate\\Log\\LogManager->driver()
#3 C:\\laragon\\www\\feelback-docker\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Exceptions\\Handler.php(375): Illuminate\\Log\\LogManager->error('Class \"Tymon\\\\JW...', Array)
#4 C:\\laragon\\www\\feelback-docker\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Exceptions\\Handler.php(336): Illuminate\\Foundation\\Exceptions\\Handler->reportThrowable(Object(Error))
#5 C:\\laragon\\www\\feelback-docker\\app\\Exceptions\\Handler.php(37): Illuminate\\Foundation\\Exceptions\\Handler->report(Object(Error))
#6 C:\\laragon\\www\\feelback-docker\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Console\\Kernel.php(617): App\\Exceptions\\Handler->report(Object(Error))
#7 C:\\laragon\\www\\feelback-docker\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Console\\Kernel.php(198): Illuminate\\Foundation\\Console\\Kernel->reportException(Object(Error))
#8 Command line code(1): Illuminate\\Foundation\\Console\\Kernel->handle(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#9 {main}
"} 
[2025-07-28 01:02:58] laravel.ERROR: Class "Tymon\JWTAuth\Providers\JWT\Provider" not found {"exception":"[object] (Error(code: 0): Class \"Tymon\\JWTAuth\\Providers\\JWT\\Provider\" not found at C:\\laragon\\www\\feelback-docker\\config\\jwt.php:134)
[stacktrace]
#0 C:\\laragon\\www\\feelback-docker\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Bootstrap\\LoadConfiguration.php(91): require()
#1 C:\\laragon\\www\\feelback-docker\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Bootstrap\\LoadConfiguration.php(72): Illuminate\\Foundation\\Bootstrap\\LoadConfiguration->loadConfigurationFile(Object(Illuminate\\Config\\Repository), 'jwt', 'C:\\\\laragon\\\\www\\\\...', Array)
#2 C:\\laragon\\www\\feelback-docker\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Bootstrap\\LoadConfiguration.php(39): Illuminate\\Foundation\\Bootstrap\\LoadConfiguration->loadConfigurationFiles(Object(Illuminate\\Foundation\\Application), Object(Illuminate\\Config\\Repository))
#3 C:\\laragon\\www\\feelback-docker\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Application.php(309): Illuminate\\Foundation\\Bootstrap\\LoadConfiguration->bootstrap(Object(Illuminate\\Foundation\\Application))
#4 C:\\laragon\\www\\feelback-docker\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Console\\Kernel.php(470): Illuminate\\Foundation\\Application->bootstrapWith(Array)
#5 C:\\laragon\\www\\feelback-docker\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Console\\Kernel.php(194): Illuminate\\Foundation\\Console\\Kernel->bootstrap()
#6 Command line code(1): Illuminate\\Foundation\\Console\\Kernel->handle(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#7 {main}
"} 
[2025-07-28 01:03:03] laravel.EMERGENCY: Unable to create configured logger. Using emergency logger. {"exception":"[object] (InvalidArgumentException(code: 0): Log [] is not defined. at C:\\laragon\\www\\feelback-docker\\vendor\\laravel\\framework\\src\\Illuminate\\Log\\LogManager.php:224)
[stacktrace]
#0 C:\\laragon\\www\\feelback-docker\\vendor\\laravel\\framework\\src\\Illuminate\\Log\\LogManager.php(138): Illuminate\\Log\\LogManager->resolve(NULL, NULL)
#1 C:\\laragon\\www\\feelback-docker\\vendor\\laravel\\framework\\src\\Illuminate\\Log\\LogManager.php(125): Illuminate\\Log\\LogManager->get(NULL)
#2 C:\\laragon\\www\\feelback-docker\\vendor\\laravel\\framework\\src\\Illuminate\\Log\\LogManager.php(693): Illuminate\\Log\\LogManager->driver()
#3 C:\\laragon\\www\\feelback-docker\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Exceptions\\Handler.php(375): Illuminate\\Log\\LogManager->error('Class \"Tymon\\\\JW...', Array)
#4 C:\\laragon\\www\\feelback-docker\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Exceptions\\Handler.php(336): Illuminate\\Foundation\\Exceptions\\Handler->reportThrowable(Object(Error))
#5 C:\\laragon\\www\\feelback-docker\\app\\Exceptions\\Handler.php(37): Illuminate\\Foundation\\Exceptions\\Handler->report(Object(Error))
#6 C:\\laragon\\www\\feelback-docker\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Console\\Kernel.php(617): App\\Exceptions\\Handler->report(Object(Error))
#7 C:\\laragon\\www\\feelback-docker\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Console\\Kernel.php(198): Illuminate\\Foundation\\Console\\Kernel->reportException(Object(Error))
#8 Command line code(1): Illuminate\\Foundation\\Console\\Kernel->handle(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#9 {main}
"} 
[2025-07-28 01:03:03] laravel.ERROR: Class "Tymon\JWTAuth\Providers\JWT\Provider" not found {"exception":"[object] (Error(code: 0): Class \"Tymon\\JWTAuth\\Providers\\JWT\\Provider\" not found at C:\\laragon\\www\\feelback-docker\\config\\jwt.php:134)
[stacktrace]
#0 C:\\laragon\\www\\feelback-docker\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Bootstrap\\LoadConfiguration.php(91): require()
#1 C:\\laragon\\www\\feelback-docker\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Bootstrap\\LoadConfiguration.php(72): Illuminate\\Foundation\\Bootstrap\\LoadConfiguration->loadConfigurationFile(Object(Illuminate\\Config\\Repository), 'jwt', 'C:\\\\laragon\\\\www\\\\...', Array)
#2 C:\\laragon\\www\\feelback-docker\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Bootstrap\\LoadConfiguration.php(39): Illuminate\\Foundation\\Bootstrap\\LoadConfiguration->loadConfigurationFiles(Object(Illuminate\\Foundation\\Application), Object(Illuminate\\Config\\Repository))
#3 C:\\laragon\\www\\feelback-docker\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Application.php(309): Illuminate\\Foundation\\Bootstrap\\LoadConfiguration->bootstrap(Object(Illuminate\\Foundation\\Application))
#4 C:\\laragon\\www\\feelback-docker\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Console\\Kernel.php(470): Illuminate\\Foundation\\Application->bootstrapWith(Array)
#5 C:\\laragon\\www\\feelback-docker\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Console\\Kernel.php(194): Illuminate\\Foundation\\Console\\Kernel->bootstrap()
#6 Command line code(1): Illuminate\\Foundation\\Console\\Kernel->handle(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#7 {main}
"} 
[2025-07-28 01:03:11] laravel.EMERGENCY: Unable to create configured logger. Using emergency logger. {"exception":"[object] (InvalidArgumentException(code: 0): Log [] is not defined. at C:\\laragon\\www\\feelback-docker\\vendor\\laravel\\framework\\src\\Illuminate\\Log\\LogManager.php:224)
[stacktrace]
#0 C:\\laragon\\www\\feelback-docker\\vendor\\laravel\\framework\\src\\Illuminate\\Log\\LogManager.php(138): Illuminate\\Log\\LogManager->resolve(NULL, NULL)
#1 C:\\laragon\\www\\feelback-docker\\vendor\\laravel\\framework\\src\\Illuminate\\Log\\LogManager.php(125): Illuminate\\Log\\LogManager->get(NULL)
#2 C:\\laragon\\www\\feelback-docker\\vendor\\laravel\\framework\\src\\Illuminate\\Log\\LogManager.php(693): Illuminate\\Log\\LogManager->driver()
#3 C:\\laragon\\www\\feelback-docker\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Exceptions\\Handler.php(375): Illuminate\\Log\\LogManager->error('Class \"Tymon\\\\JW...', Array)
#4 C:\\laragon\\www\\feelback-docker\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Exceptions\\Handler.php(336): Illuminate\\Foundation\\Exceptions\\Handler->reportThrowable(Object(Error))
#5 C:\\laragon\\www\\feelback-docker\\app\\Exceptions\\Handler.php(37): Illuminate\\Foundation\\Exceptions\\Handler->report(Object(Error))
#6 C:\\laragon\\www\\feelback-docker\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Console\\Kernel.php(617): App\\Exceptions\\Handler->report(Object(Error))
#7 C:\\laragon\\www\\feelback-docker\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Console\\Kernel.php(198): Illuminate\\Foundation\\Console\\Kernel->reportException(Object(Error))
#8 Command line code(1): Illuminate\\Foundation\\Console\\Kernel->handle(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#9 {main}
"} 
[2025-07-28 01:03:11] laravel.ERROR: Class "Tymon\JWTAuth\Providers\JWT\Provider" not found {"exception":"[object] (Error(code: 0): Class \"Tymon\\JWTAuth\\Providers\\JWT\\Provider\" not found at C:\\laragon\\www\\feelback-docker\\config\\jwt.php:134)
[stacktrace]
#0 C:\\laragon\\www\\feelback-docker\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Bootstrap\\LoadConfiguration.php(91): require()
#1 C:\\laragon\\www\\feelback-docker\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Bootstrap\\LoadConfiguration.php(72): Illuminate\\Foundation\\Bootstrap\\LoadConfiguration->loadConfigurationFile(Object(Illuminate\\Config\\Repository), 'jwt', 'C:\\\\laragon\\\\www\\\\...', Array)
#2 C:\\laragon\\www\\feelback-docker\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Bootstrap\\LoadConfiguration.php(39): Illuminate\\Foundation\\Bootstrap\\LoadConfiguration->loadConfigurationFiles(Object(Illuminate\\Foundation\\Application), Object(Illuminate\\Config\\Repository))
#3 C:\\laragon\\www\\feelback-docker\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Application.php(309): Illuminate\\Foundation\\Bootstrap\\LoadConfiguration->bootstrap(Object(Illuminate\\Foundation\\Application))
#4 C:\\laragon\\www\\feelback-docker\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Console\\Kernel.php(470): Illuminate\\Foundation\\Application->bootstrapWith(Array)
#5 C:\\laragon\\www\\feelback-docker\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Console\\Kernel.php(194): Illuminate\\Foundation\\Console\\Kernel->bootstrap()
#6 Command line code(1): Illuminate\\Foundation\\Console\\Kernel->handle(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#7 {main}
"} 
[2025-07-28 01:03:13] laravel.EMERGENCY: Unable to create configured logger. Using emergency logger. {"exception":"[object] (InvalidArgumentException(code: 0): Log [] is not defined. at C:\\laragon\\www\\feelback-docker\\vendor\\laravel\\framework\\src\\Illuminate\\Log\\LogManager.php:224)
[stacktrace]
#0 C:\\laragon\\www\\feelback-docker\\vendor\\laravel\\framework\\src\\Illuminate\\Log\\LogManager.php(138): Illuminate\\Log\\LogManager->resolve(NULL, NULL)
#1 C:\\laragon\\www\\feelback-docker\\vendor\\laravel\\framework\\src\\Illuminate\\Log\\LogManager.php(125): Illuminate\\Log\\LogManager->get(NULL)
#2 C:\\laragon\\www\\feelback-docker\\vendor\\laravel\\framework\\src\\Illuminate\\Log\\LogManager.php(693): Illuminate\\Log\\LogManager->driver()
#3 C:\\laragon\\www\\feelback-docker\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Exceptions\\Handler.php(375): Illuminate\\Log\\LogManager->error('Class \"Tymon\\\\JW...', Array)
#4 C:\\laragon\\www\\feelback-docker\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Exceptions\\Handler.php(336): Illuminate\\Foundation\\Exceptions\\Handler->reportThrowable(Object(Error))
#5 C:\\laragon\\www\\feelback-docker\\app\\Exceptions\\Handler.php(37): Illuminate\\Foundation\\Exceptions\\Handler->report(Object(Error))
#6 C:\\laragon\\www\\feelback-docker\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Console\\Kernel.php(617): App\\Exceptions\\Handler->report(Object(Error))
#7 C:\\laragon\\www\\feelback-docker\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Console\\Kernel.php(198): Illuminate\\Foundation\\Console\\Kernel->reportException(Object(Error))
#8 Command line code(1): Illuminate\\Foundation\\Console\\Kernel->handle(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#9 {main}
"} 
[2025-07-28 01:03:13] laravel.ERROR: Class "Tymon\JWTAuth\Providers\JWT\Provider" not found {"exception":"[object] (Error(code: 0): Class \"Tymon\\JWTAuth\\Providers\\JWT\\Provider\" not found at C:\\laragon\\www\\feelback-docker\\config\\jwt.php:134)
[stacktrace]
#0 C:\\laragon\\www\\feelback-docker\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Bootstrap\\LoadConfiguration.php(91): require()
#1 C:\\laragon\\www\\feelback-docker\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Bootstrap\\LoadConfiguration.php(72): Illuminate\\Foundation\\Bootstrap\\LoadConfiguration->loadConfigurationFile(Object(Illuminate\\Config\\Repository), 'jwt', 'C:\\\\laragon\\\\www\\\\...', Array)
#2 C:\\laragon\\www\\feelback-docker\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Bootstrap\\LoadConfiguration.php(39): Illuminate\\Foundation\\Bootstrap\\LoadConfiguration->loadConfigurationFiles(Object(Illuminate\\Foundation\\Application), Object(Illuminate\\Config\\Repository))
#3 C:\\laragon\\www\\feelback-docker\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Application.php(309): Illuminate\\Foundation\\Bootstrap\\LoadConfiguration->bootstrap(Object(Illuminate\\Foundation\\Application))
#4 C:\\laragon\\www\\feelback-docker\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Console\\Kernel.php(470): Illuminate\\Foundation\\Application->bootstrapWith(Array)
#5 C:\\laragon\\www\\feelback-docker\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Console\\Kernel.php(194): Illuminate\\Foundation\\Console\\Kernel->bootstrap()
#6 Command line code(1): Illuminate\\Foundation\\Console\\Kernel->handle(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#7 {main}
"} 
[2025-07-28 01:03:19] laravel.EMERGENCY: Unable to create configured logger. Using emergency logger. {"exception":"[object] (InvalidArgumentException(code: 0): Log [] is not defined. at C:\\laragon\\www\\feelback-docker\\vendor\\laravel\\framework\\src\\Illuminate\\Log\\LogManager.php:224)
[stacktrace]
#0 C:\\laragon\\www\\feelback-docker\\vendor\\laravel\\framework\\src\\Illuminate\\Log\\LogManager.php(138): Illuminate\\Log\\LogManager->resolve(NULL, NULL)
#1 C:\\laragon\\www\\feelback-docker\\vendor\\laravel\\framework\\src\\Illuminate\\Log\\LogManager.php(125): Illuminate\\Log\\LogManager->get(NULL)
#2 C:\\laragon\\www\\feelback-docker\\vendor\\laravel\\framework\\src\\Illuminate\\Log\\LogManager.php(693): Illuminate\\Log\\LogManager->driver()
#3 C:\\laragon\\www\\feelback-docker\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Exceptions\\Handler.php(375): Illuminate\\Log\\LogManager->error('Class \"Tymon\\\\JW...', Array)
#4 C:\\laragon\\www\\feelback-docker\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Exceptions\\Handler.php(336): Illuminate\\Foundation\\Exceptions\\Handler->reportThrowable(Object(Error))
#5 C:\\laragon\\www\\feelback-docker\\app\\Exceptions\\Handler.php(37): Illuminate\\Foundation\\Exceptions\\Handler->report(Object(Error))
#6 C:\\laragon\\www\\feelback-docker\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Console\\Kernel.php(617): App\\Exceptions\\Handler->report(Object(Error))
#7 C:\\laragon\\www\\feelback-docker\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Console\\Kernel.php(198): Illuminate\\Foundation\\Console\\Kernel->reportException(Object(Error))
#8 Command line code(1): Illuminate\\Foundation\\Console\\Kernel->handle(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#9 {main}
"} 
[2025-07-28 01:03:19] laravel.ERROR: Class "Tymon\JWTAuth\Providers\JWT\Provider" not found {"exception":"[object] (Error(code: 0): Class \"Tymon\\JWTAuth\\Providers\\JWT\\Provider\" not found at C:\\laragon\\www\\feelback-docker\\config\\jwt.php:134)
[stacktrace]
#0 C:\\laragon\\www\\feelback-docker\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Bootstrap\\LoadConfiguration.php(91): require()
#1 C:\\laragon\\www\\feelback-docker\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Bootstrap\\LoadConfiguration.php(72): Illuminate\\Foundation\\Bootstrap\\LoadConfiguration->loadConfigurationFile(Object(Illuminate\\Config\\Repository), 'jwt', 'C:\\\\laragon\\\\www\\\\...', Array)
#2 C:\\laragon\\www\\feelback-docker\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Bootstrap\\LoadConfiguration.php(39): Illuminate\\Foundation\\Bootstrap\\LoadConfiguration->loadConfigurationFiles(Object(Illuminate\\Foundation\\Application), Object(Illuminate\\Config\\Repository))
#3 C:\\laragon\\www\\feelback-docker\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Application.php(309): Illuminate\\Foundation\\Bootstrap\\LoadConfiguration->bootstrap(Object(Illuminate\\Foundation\\Application))
#4 C:\\laragon\\www\\feelback-docker\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Console\\Kernel.php(470): Illuminate\\Foundation\\Application->bootstrapWith(Array)
#5 C:\\laragon\\www\\feelback-docker\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Console\\Kernel.php(194): Illuminate\\Foundation\\Console\\Kernel->bootstrap()
#6 Command line code(1): Illuminate\\Foundation\\Console\\Kernel->handle(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#7 {main}
"} 
[2025-07-28 01:03:23] laravel.EMERGENCY: Unable to create configured logger. Using emergency logger. {"exception":"[object] (InvalidArgumentException(code: 0): Log [] is not defined. at C:\\laragon\\www\\feelback-docker\\vendor\\laravel\\framework\\src\\Illuminate\\Log\\LogManager.php:224)
[stacktrace]
#0 C:\\laragon\\www\\feelback-docker\\vendor\\laravel\\framework\\src\\Illuminate\\Log\\LogManager.php(138): Illuminate\\Log\\LogManager->resolve(NULL, NULL)
#1 C:\\laragon\\www\\feelback-docker\\vendor\\laravel\\framework\\src\\Illuminate\\Log\\LogManager.php(125): Illuminate\\Log\\LogManager->get(NULL)
#2 C:\\laragon\\www\\feelback-docker\\vendor\\laravel\\framework\\src\\Illuminate\\Log\\LogManager.php(693): Illuminate\\Log\\LogManager->driver()
#3 C:\\laragon\\www\\feelback-docker\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Exceptions\\Handler.php(375): Illuminate\\Log\\LogManager->error('Class \"Tymon\\\\JW...', Array)
#4 C:\\laragon\\www\\feelback-docker\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Exceptions\\Handler.php(336): Illuminate\\Foundation\\Exceptions\\Handler->reportThrowable(Object(Error))
#5 C:\\laragon\\www\\feelback-docker\\app\\Exceptions\\Handler.php(37): Illuminate\\Foundation\\Exceptions\\Handler->report(Object(Error))
#6 C:\\laragon\\www\\feelback-docker\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Console\\Kernel.php(617): App\\Exceptions\\Handler->report(Object(Error))
#7 C:\\laragon\\www\\feelback-docker\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Console\\Kernel.php(198): Illuminate\\Foundation\\Console\\Kernel->reportException(Object(Error))
#8 Command line code(1): Illuminate\\Foundation\\Console\\Kernel->handle(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#9 {main}
"} 
[2025-07-28 01:03:23] laravel.ERROR: Class "Tymon\JWTAuth\Providers\JWT\Provider" not found {"exception":"[object] (Error(code: 0): Class \"Tymon\\JWTAuth\\Providers\\JWT\\Provider\" not found at C:\\laragon\\www\\feelback-docker\\config\\jwt.php:134)
[stacktrace]
#0 C:\\laragon\\www\\feelback-docker\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Bootstrap\\LoadConfiguration.php(91): require()
#1 C:\\laragon\\www\\feelback-docker\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Bootstrap\\LoadConfiguration.php(72): Illuminate\\Foundation\\Bootstrap\\LoadConfiguration->loadConfigurationFile(Object(Illuminate\\Config\\Repository), 'jwt', 'C:\\\\laragon\\\\www\\\\...', Array)
#2 C:\\laragon\\www\\feelback-docker\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Bootstrap\\LoadConfiguration.php(39): Illuminate\\Foundation\\Bootstrap\\LoadConfiguration->loadConfigurationFiles(Object(Illuminate\\Foundation\\Application), Object(Illuminate\\Config\\Repository))
#3 C:\\laragon\\www\\feelback-docker\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Application.php(309): Illuminate\\Foundation\\Bootstrap\\LoadConfiguration->bootstrap(Object(Illuminate\\Foundation\\Application))
#4 C:\\laragon\\www\\feelback-docker\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Console\\Kernel.php(470): Illuminate\\Foundation\\Application->bootstrapWith(Array)
#5 C:\\laragon\\www\\feelback-docker\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Console\\Kernel.php(194): Illuminate\\Foundation\\Console\\Kernel->bootstrap()
#6 Command line code(1): Illuminate\\Foundation\\Console\\Kernel->handle(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#7 {main}
"} 
[2025-07-28 01:03:28] laravel.EMERGENCY: Unable to create configured logger. Using emergency logger. {"exception":"[object] (InvalidArgumentException(code: 0): Log [] is not defined. at C:\\laragon\\www\\feelback-docker\\vendor\\laravel\\framework\\src\\Illuminate\\Log\\LogManager.php:224)
[stacktrace]
#0 C:\\laragon\\www\\feelback-docker\\vendor\\laravel\\framework\\src\\Illuminate\\Log\\LogManager.php(138): Illuminate\\Log\\LogManager->resolve(NULL, NULL)
#1 C:\\laragon\\www\\feelback-docker\\vendor\\laravel\\framework\\src\\Illuminate\\Log\\LogManager.php(125): Illuminate\\Log\\LogManager->get(NULL)
#2 C:\\laragon\\www\\feelback-docker\\vendor\\laravel\\framework\\src\\Illuminate\\Log\\LogManager.php(693): Illuminate\\Log\\LogManager->driver()
#3 C:\\laragon\\www\\feelback-docker\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Exceptions\\Handler.php(375): Illuminate\\Log\\LogManager->error('Class \"Tymon\\\\JW...', Array)
#4 C:\\laragon\\www\\feelback-docker\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Exceptions\\Handler.php(336): Illuminate\\Foundation\\Exceptions\\Handler->reportThrowable(Object(Error))
#5 C:\\laragon\\www\\feelback-docker\\app\\Exceptions\\Handler.php(37): Illuminate\\Foundation\\Exceptions\\Handler->report(Object(Error))
#6 C:\\laragon\\www\\feelback-docker\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Console\\Kernel.php(617): App\\Exceptions\\Handler->report(Object(Error))
#7 C:\\laragon\\www\\feelback-docker\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Console\\Kernel.php(198): Illuminate\\Foundation\\Console\\Kernel->reportException(Object(Error))
#8 Command line code(1): Illuminate\\Foundation\\Console\\Kernel->handle(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#9 {main}
"} 
[2025-07-28 01:03:28] laravel.ERROR: Class "Tymon\JWTAuth\Providers\JWT\Provider" not found {"exception":"[object] (Error(code: 0): Class \"Tymon\\JWTAuth\\Providers\\JWT\\Provider\" not found at C:\\laragon\\www\\feelback-docker\\config\\jwt.php:134)
[stacktrace]
#0 C:\\laragon\\www\\feelback-docker\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Bootstrap\\LoadConfiguration.php(91): require()
#1 C:\\laragon\\www\\feelback-docker\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Bootstrap\\LoadConfiguration.php(72): Illuminate\\Foundation\\Bootstrap\\LoadConfiguration->loadConfigurationFile(Object(Illuminate\\Config\\Repository), 'jwt', 'C:\\\\laragon\\\\www\\\\...', Array)
#2 C:\\laragon\\www\\feelback-docker\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Bootstrap\\LoadConfiguration.php(39): Illuminate\\Foundation\\Bootstrap\\LoadConfiguration->loadConfigurationFiles(Object(Illuminate\\Foundation\\Application), Object(Illuminate\\Config\\Repository))
#3 C:\\laragon\\www\\feelback-docker\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Application.php(309): Illuminate\\Foundation\\Bootstrap\\LoadConfiguration->bootstrap(Object(Illuminate\\Foundation\\Application))
#4 C:\\laragon\\www\\feelback-docker\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Console\\Kernel.php(470): Illuminate\\Foundation\\Application->bootstrapWith(Array)
#5 C:\\laragon\\www\\feelback-docker\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Console\\Kernel.php(194): Illuminate\\Foundation\\Console\\Kernel->bootstrap()
#6 Command line code(1): Illuminate\\Foundation\\Console\\Kernel->handle(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#7 {main}
"} 
[2025-07-28 01:03:36] laravel.EMERGENCY: Unable to create configured logger. Using emergency logger. {"exception":"[object] (InvalidArgumentException(code: 0): Log [] is not defined. at C:\\laragon\\www\\feelback-docker\\vendor\\laravel\\framework\\src\\Illuminate\\Log\\LogManager.php:224)
[stacktrace]
#0 C:\\laragon\\www\\feelback-docker\\vendor\\laravel\\framework\\src\\Illuminate\\Log\\LogManager.php(138): Illuminate\\Log\\LogManager->resolve(NULL, NULL)
#1 C:\\laragon\\www\\feelback-docker\\vendor\\laravel\\framework\\src\\Illuminate\\Log\\LogManager.php(125): Illuminate\\Log\\LogManager->get(NULL)
#2 C:\\laragon\\www\\feelback-docker\\vendor\\laravel\\framework\\src\\Illuminate\\Log\\LogManager.php(693): Illuminate\\Log\\LogManager->driver()
#3 C:\\laragon\\www\\feelback-docker\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Exceptions\\Handler.php(375): Illuminate\\Log\\LogManager->error('Class \"Tymon\\\\JW...', Array)
#4 C:\\laragon\\www\\feelback-docker\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Exceptions\\Handler.php(336): Illuminate\\Foundation\\Exceptions\\Handler->reportThrowable(Object(Error))
#5 C:\\laragon\\www\\feelback-docker\\app\\Exceptions\\Handler.php(37): Illuminate\\Foundation\\Exceptions\\Handler->report(Object(Error))
#6 C:\\laragon\\www\\feelback-docker\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Console\\Kernel.php(617): App\\Exceptions\\Handler->report(Object(Error))
#7 C:\\laragon\\www\\feelback-docker\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Console\\Kernel.php(198): Illuminate\\Foundation\\Console\\Kernel->reportException(Object(Error))
#8 Command line code(1): Illuminate\\Foundation\\Console\\Kernel->handle(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#9 {main}
"} 
[2025-07-28 01:03:36] laravel.ERROR: Class "Tymon\JWTAuth\Providers\JWT\Provider" not found {"exception":"[object] (Error(code: 0): Class \"Tymon\\JWTAuth\\Providers\\JWT\\Provider\" not found at C:\\laragon\\www\\feelback-docker\\config\\jwt.php:134)
[stacktrace]
#0 C:\\laragon\\www\\feelback-docker\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Bootstrap\\LoadConfiguration.php(91): require()
#1 C:\\laragon\\www\\feelback-docker\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Bootstrap\\LoadConfiguration.php(72): Illuminate\\Foundation\\Bootstrap\\LoadConfiguration->loadConfigurationFile(Object(Illuminate\\Config\\Repository), 'jwt', 'C:\\\\laragon\\\\www\\\\...', Array)
#2 C:\\laragon\\www\\feelback-docker\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Bootstrap\\LoadConfiguration.php(39): Illuminate\\Foundation\\Bootstrap\\LoadConfiguration->loadConfigurationFiles(Object(Illuminate\\Foundation\\Application), Object(Illuminate\\Config\\Repository))
#3 C:\\laragon\\www\\feelback-docker\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Application.php(309): Illuminate\\Foundation\\Bootstrap\\LoadConfiguration->bootstrap(Object(Illuminate\\Foundation\\Application))
#4 C:\\laragon\\www\\feelback-docker\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Console\\Kernel.php(470): Illuminate\\Foundation\\Application->bootstrapWith(Array)
#5 C:\\laragon\\www\\feelback-docker\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Console\\Kernel.php(194): Illuminate\\Foundation\\Console\\Kernel->bootstrap()
#6 Command line code(1): Illuminate\\Foundation\\Console\\Kernel->handle(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#7 {main}
"} 
[2025-07-28 01:03:45] laravel.EMERGENCY: Unable to create configured logger. Using emergency logger. {"exception":"[object] (InvalidArgumentException(code: 0): Log [] is not defined. at C:\\laragon\\www\\feelback-docker\\vendor\\laravel\\framework\\src\\Illuminate\\Log\\LogManager.php:224)
[stacktrace]
#0 C:\\laragon\\www\\feelback-docker\\vendor\\laravel\\framework\\src\\Illuminate\\Log\\LogManager.php(138): Illuminate\\Log\\LogManager->resolve(NULL, NULL)
#1 C:\\laragon\\www\\feelback-docker\\vendor\\laravel\\framework\\src\\Illuminate\\Log\\LogManager.php(125): Illuminate\\Log\\LogManager->get(NULL)
#2 C:\\laragon\\www\\feelback-docker\\vendor\\laravel\\framework\\src\\Illuminate\\Log\\LogManager.php(693): Illuminate\\Log\\LogManager->driver()
#3 C:\\laragon\\www\\feelback-docker\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Exceptions\\Handler.php(375): Illuminate\\Log\\LogManager->error('Class \"Tymon\\\\JW...', Array)
#4 C:\\laragon\\www\\feelback-docker\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Exceptions\\Handler.php(336): Illuminate\\Foundation\\Exceptions\\Handler->reportThrowable(Object(Error))
#5 C:\\laragon\\www\\feelback-docker\\app\\Exceptions\\Handler.php(37): Illuminate\\Foundation\\Exceptions\\Handler->report(Object(Error))
#6 C:\\laragon\\www\\feelback-docker\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Console\\Kernel.php(617): App\\Exceptions\\Handler->report(Object(Error))
#7 C:\\laragon\\www\\feelback-docker\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Console\\Kernel.php(198): Illuminate\\Foundation\\Console\\Kernel->reportException(Object(Error))
#8 Command line code(1): Illuminate\\Foundation\\Console\\Kernel->handle(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#9 {main}
"} 
[2025-07-28 01:03:45] laravel.ERROR: Class "Tymon\JWTAuth\Providers\JWT\Provider" not found {"exception":"[object] (Error(code: 0): Class \"Tymon\\JWTAuth\\Providers\\JWT\\Provider\" not found at C:\\laragon\\www\\feelback-docker\\config\\jwt.php:134)
[stacktrace]
#0 C:\\laragon\\www\\feelback-docker\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Bootstrap\\LoadConfiguration.php(91): require()
#1 C:\\laragon\\www\\feelback-docker\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Bootstrap\\LoadConfiguration.php(72): Illuminate\\Foundation\\Bootstrap\\LoadConfiguration->loadConfigurationFile(Object(Illuminate\\Config\\Repository), 'jwt', 'C:\\\\laragon\\\\www\\\\...', Array)
#2 C:\\laragon\\www\\feelback-docker\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Bootstrap\\LoadConfiguration.php(39): Illuminate\\Foundation\\Bootstrap\\LoadConfiguration->loadConfigurationFiles(Object(Illuminate\\Foundation\\Application), Object(Illuminate\\Config\\Repository))
#3 C:\\laragon\\www\\feelback-docker\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Application.php(309): Illuminate\\Foundation\\Bootstrap\\LoadConfiguration->bootstrap(Object(Illuminate\\Foundation\\Application))
#4 C:\\laragon\\www\\feelback-docker\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Console\\Kernel.php(470): Illuminate\\Foundation\\Application->bootstrapWith(Array)
#5 C:\\laragon\\www\\feelback-docker\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Console\\Kernel.php(194): Illuminate\\Foundation\\Console\\Kernel->bootstrap()
#6 Command line code(1): Illuminate\\Foundation\\Console\\Kernel->handle(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#7 {main}
"} 
[2025-07-28 01:03:52] laravel.EMERGENCY: Unable to create configured logger. Using emergency logger. {"exception":"[object] (InvalidArgumentException(code: 0): Log [] is not defined. at C:\\laragon\\www\\feelback-docker\\vendor\\laravel\\framework\\src\\Illuminate\\Log\\LogManager.php:224)
[stacktrace]
#0 C:\\laragon\\www\\feelback-docker\\vendor\\laravel\\framework\\src\\Illuminate\\Log\\LogManager.php(138): Illuminate\\Log\\LogManager->resolve(NULL, NULL)
#1 C:\\laragon\\www\\feelback-docker\\vendor\\laravel\\framework\\src\\Illuminate\\Log\\LogManager.php(125): Illuminate\\Log\\LogManager->get(NULL)
#2 C:\\laragon\\www\\feelback-docker\\vendor\\laravel\\framework\\src\\Illuminate\\Log\\LogManager.php(693): Illuminate\\Log\\LogManager->driver()
#3 C:\\laragon\\www\\feelback-docker\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Exceptions\\Handler.php(375): Illuminate\\Log\\LogManager->error('Class \"Tymon\\\\JW...', Array)
#4 C:\\laragon\\www\\feelback-docker\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Exceptions\\Handler.php(336): Illuminate\\Foundation\\Exceptions\\Handler->reportThrowable(Object(Error))
#5 C:\\laragon\\www\\feelback-docker\\app\\Exceptions\\Handler.php(37): Illuminate\\Foundation\\Exceptions\\Handler->report(Object(Error))
#6 C:\\laragon\\www\\feelback-docker\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Console\\Kernel.php(617): App\\Exceptions\\Handler->report(Object(Error))
#7 C:\\laragon\\www\\feelback-docker\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Console\\Kernel.php(198): Illuminate\\Foundation\\Console\\Kernel->reportException(Object(Error))
#8 Command line code(1): Illuminate\\Foundation\\Console\\Kernel->handle(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#9 {main}
"} 
[2025-07-28 01:03:52] laravel.ERROR: Class "Tymon\JWTAuth\Providers\JWT\Provider" not found {"exception":"[object] (Error(code: 0): Class \"Tymon\\JWTAuth\\Providers\\JWT\\Provider\" not found at C:\\laragon\\www\\feelback-docker\\config\\jwt.php:134)
[stacktrace]
#0 C:\\laragon\\www\\feelback-docker\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Bootstrap\\LoadConfiguration.php(91): require()
#1 C:\\laragon\\www\\feelback-docker\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Bootstrap\\LoadConfiguration.php(72): Illuminate\\Foundation\\Bootstrap\\LoadConfiguration->loadConfigurationFile(Object(Illuminate\\Config\\Repository), 'jwt', 'C:\\\\laragon\\\\www\\\\...', Array)
#2 C:\\laragon\\www\\feelback-docker\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Bootstrap\\LoadConfiguration.php(39): Illuminate\\Foundation\\Bootstrap\\LoadConfiguration->loadConfigurationFiles(Object(Illuminate\\Foundation\\Application), Object(Illuminate\\Config\\Repository))
#3 C:\\laragon\\www\\feelback-docker\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Application.php(309): Illuminate\\Foundation\\Bootstrap\\LoadConfiguration->bootstrap(Object(Illuminate\\Foundation\\Application))
#4 C:\\laragon\\www\\feelback-docker\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Console\\Kernel.php(470): Illuminate\\Foundation\\Application->bootstrapWith(Array)
#5 C:\\laragon\\www\\feelback-docker\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Console\\Kernel.php(194): Illuminate\\Foundation\\Console\\Kernel->bootstrap()
#6 Command line code(1): Illuminate\\Foundation\\Console\\Kernel->handle(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#7 {main}
"} 
[2025-07-28 01:03:53] laravel.EMERGENCY: Unable to create configured logger. Using emergency logger. {"exception":"[object] (InvalidArgumentException(code: 0): Log [] is not defined. at C:\\laragon\\www\\feelback-docker\\vendor\\laravel\\framework\\src\\Illuminate\\Log\\LogManager.php:224)
[stacktrace]
#0 C:\\laragon\\www\\feelback-docker\\vendor\\laravel\\framework\\src\\Illuminate\\Log\\LogManager.php(138): Illuminate\\Log\\LogManager->resolve(NULL, NULL)
#1 C:\\laragon\\www\\feelback-docker\\vendor\\laravel\\framework\\src\\Illuminate\\Log\\LogManager.php(125): Illuminate\\Log\\LogManager->get(NULL)
#2 C:\\laragon\\www\\feelback-docker\\vendor\\laravel\\framework\\src\\Illuminate\\Log\\LogManager.php(693): Illuminate\\Log\\LogManager->driver()
#3 C:\\laragon\\www\\feelback-docker\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Exceptions\\Handler.php(375): Illuminate\\Log\\LogManager->error('Class \"Tymon\\\\JW...', Array)
#4 C:\\laragon\\www\\feelback-docker\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Exceptions\\Handler.php(336): Illuminate\\Foundation\\Exceptions\\Handler->reportThrowable(Object(Error))
#5 C:\\laragon\\www\\feelback-docker\\app\\Exceptions\\Handler.php(37): Illuminate\\Foundation\\Exceptions\\Handler->report(Object(Error))
#6 C:\\laragon\\www\\feelback-docker\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Console\\Kernel.php(617): App\\Exceptions\\Handler->report(Object(Error))
#7 C:\\laragon\\www\\feelback-docker\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Console\\Kernel.php(198): Illuminate\\Foundation\\Console\\Kernel->reportException(Object(Error))
#8 Command line code(1): Illuminate\\Foundation\\Console\\Kernel->handle(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#9 {main}
"} 
[2025-07-28 01:03:53] laravel.ERROR: Class "Tymon\JWTAuth\Providers\JWT\Provider" not found {"exception":"[object] (Error(code: 0): Class \"Tymon\\JWTAuth\\Providers\\JWT\\Provider\" not found at C:\\laragon\\www\\feelback-docker\\config\\jwt.php:134)
[stacktrace]
#0 C:\\laragon\\www\\feelback-docker\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Bootstrap\\LoadConfiguration.php(91): require()
#1 C:\\laragon\\www\\feelback-docker\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Bootstrap\\LoadConfiguration.php(72): Illuminate\\Foundation\\Bootstrap\\LoadConfiguration->loadConfigurationFile(Object(Illuminate\\Config\\Repository), 'jwt', 'C:\\\\laragon\\\\www\\\\...', Array)
#2 C:\\laragon\\www\\feelback-docker\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Bootstrap\\LoadConfiguration.php(39): Illuminate\\Foundation\\Bootstrap\\LoadConfiguration->loadConfigurationFiles(Object(Illuminate\\Foundation\\Application), Object(Illuminate\\Config\\Repository))
#3 C:\\laragon\\www\\feelback-docker\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Application.php(309): Illuminate\\Foundation\\Bootstrap\\LoadConfiguration->bootstrap(Object(Illuminate\\Foundation\\Application))
#4 C:\\laragon\\www\\feelback-docker\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Console\\Kernel.php(470): Illuminate\\Foundation\\Application->bootstrapWith(Array)
#5 C:\\laragon\\www\\feelback-docker\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Console\\Kernel.php(194): Illuminate\\Foundation\\Console\\Kernel->bootstrap()
#6 Command line code(1): Illuminate\\Foundation\\Console\\Kernel->handle(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#7 {main}
"} 
[2025-07-28 01:03:54] laravel.EMERGENCY: Unable to create configured logger. Using emergency logger. {"exception":"[object] (InvalidArgumentException(code: 0): Log [] is not defined. at C:\\laragon\\www\\feelback-docker\\vendor\\laravel\\framework\\src\\Illuminate\\Log\\LogManager.php:224)
[stacktrace]
#0 C:\\laragon\\www\\feelback-docker\\vendor\\laravel\\framework\\src\\Illuminate\\Log\\LogManager.php(138): Illuminate\\Log\\LogManager->resolve(NULL, NULL)
#1 C:\\laragon\\www\\feelback-docker\\vendor\\laravel\\framework\\src\\Illuminate\\Log\\LogManager.php(125): Illuminate\\Log\\LogManager->get(NULL)
#2 C:\\laragon\\www\\feelback-docker\\vendor\\laravel\\framework\\src\\Illuminate\\Log\\LogManager.php(693): Illuminate\\Log\\LogManager->driver()
#3 C:\\laragon\\www\\feelback-docker\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Exceptions\\Handler.php(375): Illuminate\\Log\\LogManager->error('Class \"Tymon\\\\JW...', Array)
#4 C:\\laragon\\www\\feelback-docker\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Exceptions\\Handler.php(336): Illuminate\\Foundation\\Exceptions\\Handler->reportThrowable(Object(Error))
#5 C:\\laragon\\www\\feelback-docker\\app\\Exceptions\\Handler.php(37): Illuminate\\Foundation\\Exceptions\\Handler->report(Object(Error))
#6 C:\\laragon\\www\\feelback-docker\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Console\\Kernel.php(617): App\\Exceptions\\Handler->report(Object(Error))
#7 C:\\laragon\\www\\feelback-docker\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Console\\Kernel.php(198): Illuminate\\Foundation\\Console\\Kernel->reportException(Object(Error))
#8 Command line code(1): Illuminate\\Foundation\\Console\\Kernel->handle(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#9 {main}
"} 
[2025-07-28 01:03:54] laravel.ERROR: Class "Tymon\JWTAuth\Providers\JWT\Provider" not found {"exception":"[object] (Error(code: 0): Class \"Tymon\\JWTAuth\\Providers\\JWT\\Provider\" not found at C:\\laragon\\www\\feelback-docker\\config\\jwt.php:134)
[stacktrace]
#0 C:\\laragon\\www\\feelback-docker\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Bootstrap\\LoadConfiguration.php(91): require()
#1 C:\\laragon\\www\\feelback-docker\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Bootstrap\\LoadConfiguration.php(72): Illuminate\\Foundation\\Bootstrap\\LoadConfiguration->loadConfigurationFile(Object(Illuminate\\Config\\Repository), 'jwt', 'C:\\\\laragon\\\\www\\\\...', Array)
#2 C:\\laragon\\www\\feelback-docker\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Bootstrap\\LoadConfiguration.php(39): Illuminate\\Foundation\\Bootstrap\\LoadConfiguration->loadConfigurationFiles(Object(Illuminate\\Foundation\\Application), Object(Illuminate\\Config\\Repository))
#3 C:\\laragon\\www\\feelback-docker\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Application.php(309): Illuminate\\Foundation\\Bootstrap\\LoadConfiguration->bootstrap(Object(Illuminate\\Foundation\\Application))
#4 C:\\laragon\\www\\feelback-docker\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Console\\Kernel.php(470): Illuminate\\Foundation\\Application->bootstrapWith(Array)
#5 C:\\laragon\\www\\feelback-docker\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Console\\Kernel.php(194): Illuminate\\Foundation\\Console\\Kernel->bootstrap()
#6 Command line code(1): Illuminate\\Foundation\\Console\\Kernel->handle(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#7 {main}
"} 
[2025-07-28 01:03:59] laravel.EMERGENCY: Unable to create configured logger. Using emergency logger. {"exception":"[object] (InvalidArgumentException(code: 0): Log [] is not defined. at C:\\laragon\\www\\feelback-docker\\vendor\\laravel\\framework\\src\\Illuminate\\Log\\LogManager.php:224)
[stacktrace]
#0 C:\\laragon\\www\\feelback-docker\\vendor\\laravel\\framework\\src\\Illuminate\\Log\\LogManager.php(138): Illuminate\\Log\\LogManager->resolve(NULL, NULL)
#1 C:\\laragon\\www\\feelback-docker\\vendor\\laravel\\framework\\src\\Illuminate\\Log\\LogManager.php(125): Illuminate\\Log\\LogManager->get(NULL)
#2 C:\\laragon\\www\\feelback-docker\\vendor\\laravel\\framework\\src\\Illuminate\\Log\\LogManager.php(693): Illuminate\\Log\\LogManager->driver()
#3 C:\\laragon\\www\\feelback-docker\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Exceptions\\Handler.php(375): Illuminate\\Log\\LogManager->error('Class \"Tymon\\\\JW...', Array)
#4 C:\\laragon\\www\\feelback-docker\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Exceptions\\Handler.php(336): Illuminate\\Foundation\\Exceptions\\Handler->reportThrowable(Object(Error))
#5 C:\\laragon\\www\\feelback-docker\\app\\Exceptions\\Handler.php(37): Illuminate\\Foundation\\Exceptions\\Handler->report(Object(Error))
#6 C:\\laragon\\www\\feelback-docker\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Console\\Kernel.php(617): App\\Exceptions\\Handler->report(Object(Error))
#7 C:\\laragon\\www\\feelback-docker\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Console\\Kernel.php(198): Illuminate\\Foundation\\Console\\Kernel->reportException(Object(Error))
#8 Command line code(1): Illuminate\\Foundation\\Console\\Kernel->handle(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#9 {main}
"} 
[2025-07-28 01:03:59] laravel.ERROR: Class "Tymon\JWTAuth\Providers\JWT\Provider" not found {"exception":"[object] (Error(code: 0): Class \"Tymon\\JWTAuth\\Providers\\JWT\\Provider\" not found at C:\\laragon\\www\\feelback-docker\\config\\jwt.php:134)
[stacktrace]
#0 C:\\laragon\\www\\feelback-docker\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Bootstrap\\LoadConfiguration.php(91): require()
#1 C:\\laragon\\www\\feelback-docker\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Bootstrap\\LoadConfiguration.php(72): Illuminate\\Foundation\\Bootstrap\\LoadConfiguration->loadConfigurationFile(Object(Illuminate\\Config\\Repository), 'jwt', 'C:\\\\laragon\\\\www\\\\...', Array)
#2 C:\\laragon\\www\\feelback-docker\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Bootstrap\\LoadConfiguration.php(39): Illuminate\\Foundation\\Bootstrap\\LoadConfiguration->loadConfigurationFiles(Object(Illuminate\\Foundation\\Application), Object(Illuminate\\Config\\Repository))
#3 C:\\laragon\\www\\feelback-docker\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Application.php(309): Illuminate\\Foundation\\Bootstrap\\LoadConfiguration->bootstrap(Object(Illuminate\\Foundation\\Application))
#4 C:\\laragon\\www\\feelback-docker\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Console\\Kernel.php(470): Illuminate\\Foundation\\Application->bootstrapWith(Array)
#5 C:\\laragon\\www\\feelback-docker\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Console\\Kernel.php(194): Illuminate\\Foundation\\Console\\Kernel->bootstrap()
#6 Command line code(1): Illuminate\\Foundation\\Console\\Kernel->handle(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#7 {main}
"} 
[2025-07-28 01:04:10] laravel.EMERGENCY: Unable to create configured logger. Using emergency logger. {"exception":"[object] (InvalidArgumentException(code: 0): Log [] is not defined. at C:\\laragon\\www\\feelback-docker\\vendor\\laravel\\framework\\src\\Illuminate\\Log\\LogManager.php:224)
[stacktrace]
#0 C:\\laragon\\www\\feelback-docker\\vendor\\laravel\\framework\\src\\Illuminate\\Log\\LogManager.php(138): Illuminate\\Log\\LogManager->resolve(NULL, NULL)
#1 C:\\laragon\\www\\feelback-docker\\vendor\\laravel\\framework\\src\\Illuminate\\Log\\LogManager.php(125): Illuminate\\Log\\LogManager->get(NULL)
#2 C:\\laragon\\www\\feelback-docker\\vendor\\laravel\\framework\\src\\Illuminate\\Log\\LogManager.php(693): Illuminate\\Log\\LogManager->driver()
#3 C:\\laragon\\www\\feelback-docker\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Exceptions\\Handler.php(375): Illuminate\\Log\\LogManager->error('Class \"Tymon\\\\JW...', Array)
#4 C:\\laragon\\www\\feelback-docker\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Exceptions\\Handler.php(336): Illuminate\\Foundation\\Exceptions\\Handler->reportThrowable(Object(Error))
#5 C:\\laragon\\www\\feelback-docker\\app\\Exceptions\\Handler.php(37): Illuminate\\Foundation\\Exceptions\\Handler->report(Object(Error))
#6 C:\\laragon\\www\\feelback-docker\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Console\\Kernel.php(617): App\\Exceptions\\Handler->report(Object(Error))
#7 C:\\laragon\\www\\feelback-docker\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Console\\Kernel.php(198): Illuminate\\Foundation\\Console\\Kernel->reportException(Object(Error))
#8 Command line code(1): Illuminate\\Foundation\\Console\\Kernel->handle(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#9 {main}
"} 
[2025-07-28 01:04:10] laravel.ERROR: Class "Tymon\JWTAuth\Providers\JWT\Provider" not found {"exception":"[object] (Error(code: 0): Class \"Tymon\\JWTAuth\\Providers\\JWT\\Provider\" not found at C:\\laragon\\www\\feelback-docker\\config\\jwt.php:134)
[stacktrace]
#0 C:\\laragon\\www\\feelback-docker\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Bootstrap\\LoadConfiguration.php(91): require()
#1 C:\\laragon\\www\\feelback-docker\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Bootstrap\\LoadConfiguration.php(72): Illuminate\\Foundation\\Bootstrap\\LoadConfiguration->loadConfigurationFile(Object(Illuminate\\Config\\Repository), 'jwt', 'C:\\\\laragon\\\\www\\\\...', Array)
#2 C:\\laragon\\www\\feelback-docker\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Bootstrap\\LoadConfiguration.php(39): Illuminate\\Foundation\\Bootstrap\\LoadConfiguration->loadConfigurationFiles(Object(Illuminate\\Foundation\\Application), Object(Illuminate\\Config\\Repository))
#3 C:\\laragon\\www\\feelback-docker\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Application.php(309): Illuminate\\Foundation\\Bootstrap\\LoadConfiguration->bootstrap(Object(Illuminate\\Foundation\\Application))
#4 C:\\laragon\\www\\feelback-docker\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Console\\Kernel.php(470): Illuminate\\Foundation\\Application->bootstrapWith(Array)
#5 C:\\laragon\\www\\feelback-docker\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Console\\Kernel.php(194): Illuminate\\Foundation\\Console\\Kernel->bootstrap()
#6 Command line code(1): Illuminate\\Foundation\\Console\\Kernel->handle(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#7 {main}
"} 
[2025-07-28 01:04:12] laravel.EMERGENCY: Unable to create configured logger. Using emergency logger. {"exception":"[object] (InvalidArgumentException(code: 0): Log [] is not defined. at C:\\laragon\\www\\feelback-docker\\vendor\\laravel\\framework\\src\\Illuminate\\Log\\LogManager.php:224)
[stacktrace]
#0 C:\\laragon\\www\\feelback-docker\\vendor\\laravel\\framework\\src\\Illuminate\\Log\\LogManager.php(138): Illuminate\\Log\\LogManager->resolve(NULL, NULL)
#1 C:\\laragon\\www\\feelback-docker\\vendor\\laravel\\framework\\src\\Illuminate\\Log\\LogManager.php(125): Illuminate\\Log\\LogManager->get(NULL)
#2 C:\\laragon\\www\\feelback-docker\\vendor\\laravel\\framework\\src\\Illuminate\\Log\\LogManager.php(693): Illuminate\\Log\\LogManager->driver()
#3 C:\\laragon\\www\\feelback-docker\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Exceptions\\Handler.php(375): Illuminate\\Log\\LogManager->error('Class \"Tymon\\\\JW...', Array)
#4 C:\\laragon\\www\\feelback-docker\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Exceptions\\Handler.php(336): Illuminate\\Foundation\\Exceptions\\Handler->reportThrowable(Object(Error))
#5 C:\\laragon\\www\\feelback-docker\\app\\Exceptions\\Handler.php(37): Illuminate\\Foundation\\Exceptions\\Handler->report(Object(Error))
#6 C:\\laragon\\www\\feelback-docker\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Console\\Kernel.php(617): App\\Exceptions\\Handler->report(Object(Error))
#7 C:\\laragon\\www\\feelback-docker\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Console\\Kernel.php(198): Illuminate\\Foundation\\Console\\Kernel->reportException(Object(Error))
#8 Command line code(1): Illuminate\\Foundation\\Console\\Kernel->handle(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#9 {main}
"} 
[2025-07-28 01:04:12] laravel.ERROR: Class "Tymon\JWTAuth\Providers\JWT\Provider" not found {"exception":"[object] (Error(code: 0): Class \"Tymon\\JWTAuth\\Providers\\JWT\\Provider\" not found at C:\\laragon\\www\\feelback-docker\\config\\jwt.php:134)
[stacktrace]
#0 C:\\laragon\\www\\feelback-docker\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Bootstrap\\LoadConfiguration.php(91): require()
#1 C:\\laragon\\www\\feelback-docker\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Bootstrap\\LoadConfiguration.php(72): Illuminate\\Foundation\\Bootstrap\\LoadConfiguration->loadConfigurationFile(Object(Illuminate\\Config\\Repository), 'jwt', 'C:\\\\laragon\\\\www\\\\...', Array)
#2 C:\\laragon\\www\\feelback-docker\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Bootstrap\\LoadConfiguration.php(39): Illuminate\\Foundation\\Bootstrap\\LoadConfiguration->loadConfigurationFiles(Object(Illuminate\\Foundation\\Application), Object(Illuminate\\Config\\Repository))
#3 C:\\laragon\\www\\feelback-docker\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Application.php(309): Illuminate\\Foundation\\Bootstrap\\LoadConfiguration->bootstrap(Object(Illuminate\\Foundation\\Application))
#4 C:\\laragon\\www\\feelback-docker\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Console\\Kernel.php(470): Illuminate\\Foundation\\Application->bootstrapWith(Array)
#5 C:\\laragon\\www\\feelback-docker\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Console\\Kernel.php(194): Illuminate\\Foundation\\Console\\Kernel->bootstrap()
#6 Command line code(1): Illuminate\\Foundation\\Console\\Kernel->handle(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#7 {main}
"} 
[2025-07-28 01:04:16] laravel.EMERGENCY: Unable to create configured logger. Using emergency logger. {"exception":"[object] (InvalidArgumentException(code: 0): Log [] is not defined. at C:\\laragon\\www\\feelback-docker\\vendor\\laravel\\framework\\src\\Illuminate\\Log\\LogManager.php:224)
[stacktrace]
#0 C:\\laragon\\www\\feelback-docker\\vendor\\laravel\\framework\\src\\Illuminate\\Log\\LogManager.php(138): Illuminate\\Log\\LogManager->resolve(NULL, NULL)
#1 C:\\laragon\\www\\feelback-docker\\vendor\\laravel\\framework\\src\\Illuminate\\Log\\LogManager.php(125): Illuminate\\Log\\LogManager->get(NULL)
#2 C:\\laragon\\www\\feelback-docker\\vendor\\laravel\\framework\\src\\Illuminate\\Log\\LogManager.php(693): Illuminate\\Log\\LogManager->driver()
#3 C:\\laragon\\www\\feelback-docker\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Exceptions\\Handler.php(375): Illuminate\\Log\\LogManager->error('Class \"Tymon\\\\JW...', Array)
#4 C:\\laragon\\www\\feelback-docker\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Exceptions\\Handler.php(336): Illuminate\\Foundation\\Exceptions\\Handler->reportThrowable(Object(Error))
#5 C:\\laragon\\www\\feelback-docker\\app\\Exceptions\\Handler.php(37): Illuminate\\Foundation\\Exceptions\\Handler->report(Object(Error))
#6 C:\\laragon\\www\\feelback-docker\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Console\\Kernel.php(617): App\\Exceptions\\Handler->report(Object(Error))
#7 C:\\laragon\\www\\feelback-docker\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Console\\Kernel.php(198): Illuminate\\Foundation\\Console\\Kernel->reportException(Object(Error))
#8 Command line code(1): Illuminate\\Foundation\\Console\\Kernel->handle(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#9 {main}
"} 
[2025-07-28 01:04:17] laravel.ERROR: Class "Tymon\JWTAuth\Providers\JWT\Provider" not found {"exception":"[object] (Error(code: 0): Class \"Tymon\\JWTAuth\\Providers\\JWT\\Provider\" not found at C:\\laragon\\www\\feelback-docker\\config\\jwt.php:134)
[stacktrace]
#0 C:\\laragon\\www\\feelback-docker\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Bootstrap\\LoadConfiguration.php(91): require()
#1 C:\\laragon\\www\\feelback-docker\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Bootstrap\\LoadConfiguration.php(72): Illuminate\\Foundation\\Bootstrap\\LoadConfiguration->loadConfigurationFile(Object(Illuminate\\Config\\Repository), 'jwt', 'C:\\\\laragon\\\\www\\\\...', Array)
#2 C:\\laragon\\www\\feelback-docker\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Bootstrap\\LoadConfiguration.php(39): Illuminate\\Foundation\\Bootstrap\\LoadConfiguration->loadConfigurationFiles(Object(Illuminate\\Foundation\\Application), Object(Illuminate\\Config\\Repository))
#3 C:\\laragon\\www\\feelback-docker\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Application.php(309): Illuminate\\Foundation\\Bootstrap\\LoadConfiguration->bootstrap(Object(Illuminate\\Foundation\\Application))
#4 C:\\laragon\\www\\feelback-docker\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Console\\Kernel.php(470): Illuminate\\Foundation\\Application->bootstrapWith(Array)
#5 C:\\laragon\\www\\feelback-docker\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Console\\Kernel.php(194): Illuminate\\Foundation\\Console\\Kernel->bootstrap()
#6 Command line code(1): Illuminate\\Foundation\\Console\\Kernel->handle(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#7 {main}
"} 
[2025-07-28 01:04:19] laravel.EMERGENCY: Unable to create configured logger. Using emergency logger. {"exception":"[object] (InvalidArgumentException(code: 0): Log [] is not defined. at C:\\laragon\\www\\feelback-docker\\vendor\\laravel\\framework\\src\\Illuminate\\Log\\LogManager.php:224)
[stacktrace]
#0 C:\\laragon\\www\\feelback-docker\\vendor\\laravel\\framework\\src\\Illuminate\\Log\\LogManager.php(138): Illuminate\\Log\\LogManager->resolve(NULL, NULL)
#1 C:\\laragon\\www\\feelback-docker\\vendor\\laravel\\framework\\src\\Illuminate\\Log\\LogManager.php(125): Illuminate\\Log\\LogManager->get(NULL)
#2 C:\\laragon\\www\\feelback-docker\\vendor\\laravel\\framework\\src\\Illuminate\\Log\\LogManager.php(693): Illuminate\\Log\\LogManager->driver()
#3 C:\\laragon\\www\\feelback-docker\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Exceptions\\Handler.php(375): Illuminate\\Log\\LogManager->error('Class \"Tymon\\\\JW...', Array)
#4 C:\\laragon\\www\\feelback-docker\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Exceptions\\Handler.php(336): Illuminate\\Foundation\\Exceptions\\Handler->reportThrowable(Object(Error))
#5 C:\\laragon\\www\\feelback-docker\\app\\Exceptions\\Handler.php(37): Illuminate\\Foundation\\Exceptions\\Handler->report(Object(Error))
#6 C:\\laragon\\www\\feelback-docker\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Console\\Kernel.php(617): App\\Exceptions\\Handler->report(Object(Error))
#7 C:\\laragon\\www\\feelback-docker\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Console\\Kernel.php(198): Illuminate\\Foundation\\Console\\Kernel->reportException(Object(Error))
#8 Command line code(1): Illuminate\\Foundation\\Console\\Kernel->handle(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#9 {main}
"} 
[2025-07-28 01:04:19] laravel.ERROR: Class "Tymon\JWTAuth\Providers\JWT\Provider" not found {"exception":"[object] (Error(code: 0): Class \"Tymon\\JWTAuth\\Providers\\JWT\\Provider\" not found at C:\\laragon\\www\\feelback-docker\\config\\jwt.php:134)
[stacktrace]
#0 C:\\laragon\\www\\feelback-docker\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Bootstrap\\LoadConfiguration.php(91): require()
#1 C:\\laragon\\www\\feelback-docker\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Bootstrap\\LoadConfiguration.php(72): Illuminate\\Foundation\\Bootstrap\\LoadConfiguration->loadConfigurationFile(Object(Illuminate\\Config\\Repository), 'jwt', 'C:\\\\laragon\\\\www\\\\...', Array)
#2 C:\\laragon\\www\\feelback-docker\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Bootstrap\\LoadConfiguration.php(39): Illuminate\\Foundation\\Bootstrap\\LoadConfiguration->loadConfigurationFiles(Object(Illuminate\\Foundation\\Application), Object(Illuminate\\Config\\Repository))
#3 C:\\laragon\\www\\feelback-docker\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Application.php(309): Illuminate\\Foundation\\Bootstrap\\LoadConfiguration->bootstrap(Object(Illuminate\\Foundation\\Application))
#4 C:\\laragon\\www\\feelback-docker\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Console\\Kernel.php(470): Illuminate\\Foundation\\Application->bootstrapWith(Array)
#5 C:\\laragon\\www\\feelback-docker\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Console\\Kernel.php(194): Illuminate\\Foundation\\Console\\Kernel->bootstrap()
#6 Command line code(1): Illuminate\\Foundation\\Console\\Kernel->handle(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#7 {main}
"} 
[2025-07-28 01:04:24] laravel.EMERGENCY: Unable to create configured logger. Using emergency logger. {"exception":"[object] (InvalidArgumentException(code: 0): Log [] is not defined. at C:\\laragon\\www\\feelback-docker\\vendor\\laravel\\framework\\src\\Illuminate\\Log\\LogManager.php:224)
[stacktrace]
#0 C:\\laragon\\www\\feelback-docker\\vendor\\laravel\\framework\\src\\Illuminate\\Log\\LogManager.php(138): Illuminate\\Log\\LogManager->resolve(NULL, NULL)
#1 C:\\laragon\\www\\feelback-docker\\vendor\\laravel\\framework\\src\\Illuminate\\Log\\LogManager.php(125): Illuminate\\Log\\LogManager->get(NULL)
#2 C:\\laragon\\www\\feelback-docker\\vendor\\laravel\\framework\\src\\Illuminate\\Log\\LogManager.php(693): Illuminate\\Log\\LogManager->driver()
#3 C:\\laragon\\www\\feelback-docker\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Exceptions\\Handler.php(375): Illuminate\\Log\\LogManager->error('Class \"Tymon\\\\JW...', Array)
#4 C:\\laragon\\www\\feelback-docker\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Exceptions\\Handler.php(336): Illuminate\\Foundation\\Exceptions\\Handler->reportThrowable(Object(Error))
#5 C:\\laragon\\www\\feelback-docker\\app\\Exceptions\\Handler.php(37): Illuminate\\Foundation\\Exceptions\\Handler->report(Object(Error))
#6 C:\\laragon\\www\\feelback-docker\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Console\\Kernel.php(617): App\\Exceptions\\Handler->report(Object(Error))
#7 C:\\laragon\\www\\feelback-docker\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Console\\Kernel.php(198): Illuminate\\Foundation\\Console\\Kernel->reportException(Object(Error))
#8 Command line code(1): Illuminate\\Foundation\\Console\\Kernel->handle(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#9 {main}
"} 
[2025-07-28 01:04:24] laravel.ERROR: Class "Tymon\JWTAuth\Providers\JWT\Provider" not found {"exception":"[object] (Error(code: 0): Class \"Tymon\\JWTAuth\\Providers\\JWT\\Provider\" not found at C:\\laragon\\www\\feelback-docker\\config\\jwt.php:134)
[stacktrace]
#0 C:\\laragon\\www\\feelback-docker\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Bootstrap\\LoadConfiguration.php(91): require()
#1 C:\\laragon\\www\\feelback-docker\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Bootstrap\\LoadConfiguration.php(72): Illuminate\\Foundation\\Bootstrap\\LoadConfiguration->loadConfigurationFile(Object(Illuminate\\Config\\Repository), 'jwt', 'C:\\\\laragon\\\\www\\\\...', Array)
#2 C:\\laragon\\www\\feelback-docker\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Bootstrap\\LoadConfiguration.php(39): Illuminate\\Foundation\\Bootstrap\\LoadConfiguration->loadConfigurationFiles(Object(Illuminate\\Foundation\\Application), Object(Illuminate\\Config\\Repository))
#3 C:\\laragon\\www\\feelback-docker\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Application.php(309): Illuminate\\Foundation\\Bootstrap\\LoadConfiguration->bootstrap(Object(Illuminate\\Foundation\\Application))
#4 C:\\laragon\\www\\feelback-docker\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Console\\Kernel.php(470): Illuminate\\Foundation\\Application->bootstrapWith(Array)
#5 C:\\laragon\\www\\feelback-docker\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Console\\Kernel.php(194): Illuminate\\Foundation\\Console\\Kernel->bootstrap()
#6 Command line code(1): Illuminate\\Foundation\\Console\\Kernel->handle(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#7 {main}
"} 
[2025-07-28 01:04:30] laravel.EMERGENCY: Unable to create configured logger. Using emergency logger. {"exception":"[object] (InvalidArgumentException(code: 0): Log [] is not defined. at C:\\laragon\\www\\feelback-docker\\vendor\\laravel\\framework\\src\\Illuminate\\Log\\LogManager.php:224)
[stacktrace]
#0 C:\\laragon\\www\\feelback-docker\\vendor\\laravel\\framework\\src\\Illuminate\\Log\\LogManager.php(138): Illuminate\\Log\\LogManager->resolve(NULL, NULL)
#1 C:\\laragon\\www\\feelback-docker\\vendor\\laravel\\framework\\src\\Illuminate\\Log\\LogManager.php(125): Illuminate\\Log\\LogManager->get(NULL)
#2 C:\\laragon\\www\\feelback-docker\\vendor\\laravel\\framework\\src\\Illuminate\\Log\\LogManager.php(693): Illuminate\\Log\\LogManager->driver()
#3 C:\\laragon\\www\\feelback-docker\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Exceptions\\Handler.php(375): Illuminate\\Log\\LogManager->error('Class \"Tymon\\\\JW...', Array)
#4 C:\\laragon\\www\\feelback-docker\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Exceptions\\Handler.php(336): Illuminate\\Foundation\\Exceptions\\Handler->reportThrowable(Object(Error))
#5 C:\\laragon\\www\\feelback-docker\\app\\Exceptions\\Handler.php(37): Illuminate\\Foundation\\Exceptions\\Handler->report(Object(Error))
#6 C:\\laragon\\www\\feelback-docker\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Console\\Kernel.php(617): App\\Exceptions\\Handler->report(Object(Error))
#7 C:\\laragon\\www\\feelback-docker\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Console\\Kernel.php(198): Illuminate\\Foundation\\Console\\Kernel->reportException(Object(Error))
#8 Command line code(1): Illuminate\\Foundation\\Console\\Kernel->handle(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#9 {main}
"} 
[2025-07-28 01:04:30] laravel.ERROR: Class "Tymon\JWTAuth\Providers\JWT\Provider" not found {"exception":"[object] (Error(code: 0): Class \"Tymon\\JWTAuth\\Providers\\JWT\\Provider\" not found at C:\\laragon\\www\\feelback-docker\\config\\jwt.php:134)
[stacktrace]
#0 C:\\laragon\\www\\feelback-docker\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Bootstrap\\LoadConfiguration.php(91): require()
#1 C:\\laragon\\www\\feelback-docker\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Bootstrap\\LoadConfiguration.php(72): Illuminate\\Foundation\\Bootstrap\\LoadConfiguration->loadConfigurationFile(Object(Illuminate\\Config\\Repository), 'jwt', 'C:\\\\laragon\\\\www\\\\...', Array)
#2 C:\\laragon\\www\\feelback-docker\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Bootstrap\\LoadConfiguration.php(39): Illuminate\\Foundation\\Bootstrap\\LoadConfiguration->loadConfigurationFiles(Object(Illuminate\\Foundation\\Application), Object(Illuminate\\Config\\Repository))
#3 C:\\laragon\\www\\feelback-docker\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Application.php(309): Illuminate\\Foundation\\Bootstrap\\LoadConfiguration->bootstrap(Object(Illuminate\\Foundation\\Application))
#4 C:\\laragon\\www\\feelback-docker\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Console\\Kernel.php(470): Illuminate\\Foundation\\Application->bootstrapWith(Array)
#5 C:\\laragon\\www\\feelback-docker\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Console\\Kernel.php(194): Illuminate\\Foundation\\Console\\Kernel->bootstrap()
#6 Command line code(1): Illuminate\\Foundation\\Console\\Kernel->handle(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#7 {main}
"} 
[2025-07-28 01:04:32] laravel.EMERGENCY: Unable to create configured logger. Using emergency logger. {"exception":"[object] (InvalidArgumentException(code: 0): Log [] is not defined. at C:\\laragon\\www\\feelback-docker\\vendor\\laravel\\framework\\src\\Illuminate\\Log\\LogManager.php:224)
[stacktrace]
#0 C:\\laragon\\www\\feelback-docker\\vendor\\laravel\\framework\\src\\Illuminate\\Log\\LogManager.php(138): Illuminate\\Log\\LogManager->resolve(NULL, NULL)
#1 C:\\laragon\\www\\feelback-docker\\vendor\\laravel\\framework\\src\\Illuminate\\Log\\LogManager.php(125): Illuminate\\Log\\LogManager->get(NULL)
#2 C:\\laragon\\www\\feelback-docker\\vendor\\laravel\\framework\\src\\Illuminate\\Log\\LogManager.php(693): Illuminate\\Log\\LogManager->driver()
#3 C:\\laragon\\www\\feelback-docker\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Exceptions\\Handler.php(375): Illuminate\\Log\\LogManager->error('Class \"Tymon\\\\JW...', Array)
#4 C:\\laragon\\www\\feelback-docker\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Exceptions\\Handler.php(336): Illuminate\\Foundation\\Exceptions\\Handler->reportThrowable(Object(Error))
#5 C:\\laragon\\www\\feelback-docker\\app\\Exceptions\\Handler.php(37): Illuminate\\Foundation\\Exceptions\\Handler->report(Object(Error))
#6 C:\\laragon\\www\\feelback-docker\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Console\\Kernel.php(617): App\\Exceptions\\Handler->report(Object(Error))
#7 C:\\laragon\\www\\feelback-docker\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Console\\Kernel.php(198): Illuminate\\Foundation\\Console\\Kernel->reportException(Object(Error))
#8 Command line code(1): Illuminate\\Foundation\\Console\\Kernel->handle(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#9 {main}
"} 
[2025-07-28 01:04:32] laravel.ERROR: Class "Tymon\JWTAuth\Providers\JWT\Provider" not found {"exception":"[object] (Error(code: 0): Class \"Tymon\\JWTAuth\\Providers\\JWT\\Provider\" not found at C:\\laragon\\www\\feelback-docker\\config\\jwt.php:134)
[stacktrace]
#0 C:\\laragon\\www\\feelback-docker\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Bootstrap\\LoadConfiguration.php(91): require()
#1 C:\\laragon\\www\\feelback-docker\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Bootstrap\\LoadConfiguration.php(72): Illuminate\\Foundation\\Bootstrap\\LoadConfiguration->loadConfigurationFile(Object(Illuminate\\Config\\Repository), 'jwt', 'C:\\\\laragon\\\\www\\\\...', Array)
#2 C:\\laragon\\www\\feelback-docker\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Bootstrap\\LoadConfiguration.php(39): Illuminate\\Foundation\\Bootstrap\\LoadConfiguration->loadConfigurationFiles(Object(Illuminate\\Foundation\\Application), Object(Illuminate\\Config\\Repository))
#3 C:\\laragon\\www\\feelback-docker\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Application.php(309): Illuminate\\Foundation\\Bootstrap\\LoadConfiguration->bootstrap(Object(Illuminate\\Foundation\\Application))
#4 C:\\laragon\\www\\feelback-docker\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Console\\Kernel.php(470): Illuminate\\Foundation\\Application->bootstrapWith(Array)
#5 C:\\laragon\\www\\feelback-docker\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Console\\Kernel.php(194): Illuminate\\Foundation\\Console\\Kernel->bootstrap()
#6 Command line code(1): Illuminate\\Foundation\\Console\\Kernel->handle(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#7 {main}
"} 
[2025-07-28 01:04:34] laravel.EMERGENCY: Unable to create configured logger. Using emergency logger. {"exception":"[object] (InvalidArgumentException(code: 0): Log [] is not defined. at C:\\laragon\\www\\feelback-docker\\vendor\\laravel\\framework\\src\\Illuminate\\Log\\LogManager.php:224)
[stacktrace]
#0 C:\\laragon\\www\\feelback-docker\\vendor\\laravel\\framework\\src\\Illuminate\\Log\\LogManager.php(138): Illuminate\\Log\\LogManager->resolve(NULL, NULL)
#1 C:\\laragon\\www\\feelback-docker\\vendor\\laravel\\framework\\src\\Illuminate\\Log\\LogManager.php(125): Illuminate\\Log\\LogManager->get(NULL)
#2 C:\\laragon\\www\\feelback-docker\\vendor\\laravel\\framework\\src\\Illuminate\\Log\\LogManager.php(693): Illuminate\\Log\\LogManager->driver()
#3 C:\\laragon\\www\\feelback-docker\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Exceptions\\Handler.php(375): Illuminate\\Log\\LogManager->error('Class \"Tymon\\\\JW...', Array)
#4 C:\\laragon\\www\\feelback-docker\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Exceptions\\Handler.php(336): Illuminate\\Foundation\\Exceptions\\Handler->reportThrowable(Object(Error))
#5 C:\\laragon\\www\\feelback-docker\\app\\Exceptions\\Handler.php(37): Illuminate\\Foundation\\Exceptions\\Handler->report(Object(Error))
#6 C:\\laragon\\www\\feelback-docker\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Console\\Kernel.php(617): App\\Exceptions\\Handler->report(Object(Error))
#7 C:\\laragon\\www\\feelback-docker\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Console\\Kernel.php(198): Illuminate\\Foundation\\Console\\Kernel->reportException(Object(Error))
#8 Command line code(1): Illuminate\\Foundation\\Console\\Kernel->handle(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#9 {main}
"} 
[2025-07-28 01:04:34] laravel.ERROR: Class "Tymon\JWTAuth\Providers\JWT\Provider" not found {"exception":"[object] (Error(code: 0): Class \"Tymon\\JWTAuth\\Providers\\JWT\\Provider\" not found at C:\\laragon\\www\\feelback-docker\\config\\jwt.php:134)
[stacktrace]
#0 C:\\laragon\\www\\feelback-docker\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Bootstrap\\LoadConfiguration.php(91): require()
#1 C:\\laragon\\www\\feelback-docker\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Bootstrap\\LoadConfiguration.php(72): Illuminate\\Foundation\\Bootstrap\\LoadConfiguration->loadConfigurationFile(Object(Illuminate\\Config\\Repository), 'jwt', 'C:\\\\laragon\\\\www\\\\...', Array)
#2 C:\\laragon\\www\\feelback-docker\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Bootstrap\\LoadConfiguration.php(39): Illuminate\\Foundation\\Bootstrap\\LoadConfiguration->loadConfigurationFiles(Object(Illuminate\\Foundation\\Application), Object(Illuminate\\Config\\Repository))
#3 C:\\laragon\\www\\feelback-docker\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Application.php(309): Illuminate\\Foundation\\Bootstrap\\LoadConfiguration->bootstrap(Object(Illuminate\\Foundation\\Application))
#4 C:\\laragon\\www\\feelback-docker\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Console\\Kernel.php(470): Illuminate\\Foundation\\Application->bootstrapWith(Array)
#5 C:\\laragon\\www\\feelback-docker\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Console\\Kernel.php(194): Illuminate\\Foundation\\Console\\Kernel->bootstrap()
#6 Command line code(1): Illuminate\\Foundation\\Console\\Kernel->handle(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#7 {main}
"} 
[2025-07-28 01:04:39] laravel.EMERGENCY: Unable to create configured logger. Using emergency logger. {"exception":"[object] (InvalidArgumentException(code: 0): Log [] is not defined. at C:\\laragon\\www\\feelback-docker\\vendor\\laravel\\framework\\src\\Illuminate\\Log\\LogManager.php:224)
[stacktrace]
#0 C:\\laragon\\www\\feelback-docker\\vendor\\laravel\\framework\\src\\Illuminate\\Log\\LogManager.php(138): Illuminate\\Log\\LogManager->resolve(NULL, NULL)
#1 C:\\laragon\\www\\feelback-docker\\vendor\\laravel\\framework\\src\\Illuminate\\Log\\LogManager.php(125): Illuminate\\Log\\LogManager->get(NULL)
#2 C:\\laragon\\www\\feelback-docker\\vendor\\laravel\\framework\\src\\Illuminate\\Log\\LogManager.php(693): Illuminate\\Log\\LogManager->driver()
#3 C:\\laragon\\www\\feelback-docker\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Exceptions\\Handler.php(375): Illuminate\\Log\\LogManager->error('Class \"Tymon\\\\JW...', Array)
#4 C:\\laragon\\www\\feelback-docker\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Exceptions\\Handler.php(336): Illuminate\\Foundation\\Exceptions\\Handler->reportThrowable(Object(Error))
#5 C:\\laragon\\www\\feelback-docker\\app\\Exceptions\\Handler.php(37): Illuminate\\Foundation\\Exceptions\\Handler->report(Object(Error))
#6 C:\\laragon\\www\\feelback-docker\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Console\\Kernel.php(617): App\\Exceptions\\Handler->report(Object(Error))
#7 C:\\laragon\\www\\feelback-docker\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Console\\Kernel.php(198): Illuminate\\Foundation\\Console\\Kernel->reportException(Object(Error))
#8 Command line code(1): Illuminate\\Foundation\\Console\\Kernel->handle(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#9 {main}
"} 
[2025-07-28 01:04:39] laravel.ERROR: Class "Tymon\JWTAuth\Providers\JWT\Provider" not found {"exception":"[object] (Error(code: 0): Class \"Tymon\\JWTAuth\\Providers\\JWT\\Provider\" not found at C:\\laragon\\www\\feelback-docker\\config\\jwt.php:134)
[stacktrace]
#0 C:\\laragon\\www\\feelback-docker\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Bootstrap\\LoadConfiguration.php(91): require()
#1 C:\\laragon\\www\\feelback-docker\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Bootstrap\\LoadConfiguration.php(72): Illuminate\\Foundation\\Bootstrap\\LoadConfiguration->loadConfigurationFile(Object(Illuminate\\Config\\Repository), 'jwt', 'C:\\\\laragon\\\\www\\\\...', Array)
#2 C:\\laragon\\www\\feelback-docker\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Bootstrap\\LoadConfiguration.php(39): Illuminate\\Foundation\\Bootstrap\\LoadConfiguration->loadConfigurationFiles(Object(Illuminate\\Foundation\\Application), Object(Illuminate\\Config\\Repository))
#3 C:\\laragon\\www\\feelback-docker\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Application.php(309): Illuminate\\Foundation\\Bootstrap\\LoadConfiguration->bootstrap(Object(Illuminate\\Foundation\\Application))
#4 C:\\laragon\\www\\feelback-docker\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Console\\Kernel.php(470): Illuminate\\Foundation\\Application->bootstrapWith(Array)
#5 C:\\laragon\\www\\feelback-docker\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Console\\Kernel.php(194): Illuminate\\Foundation\\Console\\Kernel->bootstrap()
#6 Command line code(1): Illuminate\\Foundation\\Console\\Kernel->handle(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#7 {main}
"} 
